name: CI to Azure Container Registry

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: eventpix.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t eventpix.azurecr.io/eventpix-api:latest
          docker push eventpix.azurecr.io/eventpix-api:latest
